version: "3.9"

services:
  frontend:
    build: ./frontend_service
    ports:
      - "5000:5000"
    depends_on:
      - excel_parser
      - grades_service
    environment:
      - EXCEL_PARSER_URL=http://excel_parser:5001
      - GRADE_SERVICE_URL=http://grades_service:5002

  excel_parser:
    build: ./excel_parser_service
    ports:
      - "5001:5001"

  grades_service:
    build: ./grades_service
    ports:
      - "5002:5002"
    volumes:
      - grades_data:/app/grades.db

volumes:
  grades_data:
